blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/orgs/gtt-project/discussions
    about: Ask questions and share ideas with the community.
  - name: Website
    url: https://gtt-project.org
    about: Learn more about the GTT Project.
